DROP TABLE IF EXISTS KONYV;
 
CREATE TABLE KONYV (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cim VARCHAR(250) NOT NULL,
  szerzo VARCHAR(250) NOT NULL
  );
 
INSERT INTO KONYV (cim, szerzo) VALUES('TestCim1', 'TestAuthor1');
INSERT INTO KONYV (cim, szerzo) VALUES('TestCim2', 'TestAuthor2');
